import Head from "next/head";
import Link from 'next/link';
import styles from "@/styles/Home.module.css";
import { Post } from "@/types";

type Props = {
  posts: Post[];
};

//  getStaticProps は Next.js の関数で、ページをビルド時に一度だけ実行されます。この関数は、APIや外部データベースからデータを取得して、ビルド時に静的なページを生成する際に使用されます。
export async function getStaticProps() {
  // fetch 関数は、指定されたURLからHTTPリクエストを送り、レスポンスを待ちます。
  const res = await fetch("http://127.0.0.1:3001/api/v1/posts");
  const posts = await res.json();

  console.log(posts);

  // return 文で、posts を props オブジェクトとして返します。これにより、コンポーネント内で props.posts として取得したデータを使用することができます。
  return{
    props: {
      posts,
    },
    revalidate: 60 * 60 * 24,
  }
}

export default function Home({posts}: Props ) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {posts.map((post: Post) => (
          <div key={post.id} className={styles.postCard}>
            <Link href={`posts/${post.id}`} className={styles.postCardBox}>
              <h2>{post.title}</h2>
            </Link>
            <p>{post.content}</p>
            <button className={styles.editButton}>Edit</button>
            <button className={styles.deleteButton}>Delete</button>
          </div>
        ))}
      </div>
    </>
  );
}
